services:
    lmsbooks:
        image: lmsbooks:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8087-8090:8080"
        environment:
            SPRING_PROFILES_ACTIVE: test, bootstrap, relational, IDService1
        networks:
            - lms_network2
        volumes:
            - "uploaded_files_volume_bookscommand:/tmp"
        deploy:
            mode: replicated
            replicas: 2

    postgres_in_lms_network:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        deploy:
            replicas: 2
        ports:
            - "5432-5436:5432"
        volumes:
            - "postgres_volume:/var/lib/postgresql/data"
        networks:
            - lms_network2
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres" ]
            interval: 10s
            retries: 5
            timeout: 5s

    nginx_bookCommand:
        image: nginx:latest
        restart: unless-stopped
        deploy:
            replicas: 1
        ports:
            - "83:80"
            - "446:443"
        networks:
            - lms_network2
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

networks:
    lms_network2:
        external: true

volumes:
    uploaded_files_volume_bookscommand:
    postgres_volume:
