services:
    lmsbooks:
        image: lmsbooks:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8087:8080"
        environment:
            SPRING_PROFILES_ACTIVE: bootstrap, relational, IDService1
        networks:
            - lms_network2
        volumes:
            - "uploaded_files_volume_bookscommand:/tmp"

    postgres_in_lms_network:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "5423:5432"
        volumes:
            - "postgres_volume_34:/var/lib/postgresql/data"
        networks:
            - lms_network2
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres" ]
            interval: 10s
            retries: 5
            timeout: 5s

networks:
    lms_network2:
        external: true

volumes:
    uploaded_files_volume_bookscommand:
    postgres_volume_34:
