global:
  scrape_interval: 15s

# Configuração do remote_write (fora de scrape_configs)
remote_write:
  #- url:
   # basic_auth:
    #  username: "------"
     # password: "------"
scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'docker-swarm'
    tls_config:
      insecure_skip_verify: true
    dockerswarm_sd_configs:
      - host: 'tcp://host.docker.internal:2375'
        role: 'tasks'
    metrics_path: /actuator/prometheus
    relabel_configs:
      # Exclui todos os serviços que começam com "monitoring"
      - source_labels: [__meta_dockerswarm_service_name]
        regex: 'monitoring_.*'
        action: drop

      # Remove tudo antes do primeiro underscore no nome do serviço e substitui o __address__
      - source_labels: [__meta_dockerswarm_service_name]
        regex: '[^_]*_(.*)'
        target_label: __address__
        replacement: '${1}:8080'  # Substitui "<service_name>:8080" sem o prefixo

      # Define o rótulo 'instance' com o nome do serviço sem o prefixo
      - source_labels: [__meta_dockerswarm_service_name]
        regex: '[^_]*_(.*)'
        target_label: instance
        replacement: '${1}'
