services:
    bookquery:
        image: bookquery:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8085:8080"
        environment:
            SPRING_PROFILES_ACTIVE: bootstrap, relational, IDService1
        networks:
            - lms_network2
        volumes:
            - "uploaded_files_volume_bookquery:/tmp"
        deploy:
            mode: replicated
            replicas: 2

    mongo_in_lms_network:
        image: mongo:latest
        ports:
            - "27017-27023:27017" # Porta do MongoDB exposta para o host
        volumes:
            - mongo_data:/data/db # Persistência de dados
        networks:
            - lms_network2
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        deploy:
            mode: replicated
            replicas: 1
        healthcheck:
            test: ["CMD", "mongo", "--eval"]
            interval: 10s
            retries: 5
            timeout: 5s


networks:
    lms_network2:
        external: true

volumes:
    uploaded_files_volume_bookquery:
    postgres_volume:
    mongo_data: