services:
    lmsbooksquery:
        image: lmsbooksquery:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8088:8080"
        environment:
            SPRING_PROFILES_ACTIVE: bootstrap, mongo, IDService1
            SPRING_DATA_MONGODB_URI: mongodb://mongo_in_lms_network:27017/?directConnection=true
            SPRING_DATA_MONGODB_DATABASE: bookQuery_${HOSTNAME:-default}
        networks:
            - lms_network2
        volumes:
            - "uploaded_files_volume_booksquery:/tmp"
        deploy:
            mode: replicated
            replicas: 2

networks:
    lms_network2:
        external: true

volumes:
    uploaded_files_volume_booksquery: