package pt.psoft.g1.psoftg1.shared.model;

public interface LendingEvents {
    String LENDING_CREATED_BOOK = "LENDING_CREATED_BOOK";

    String LENDING_CREATED_READER_FINAL = "LENDING_CREATED_READER_FINAL";
    String LENDING_RETURNED = "LENDING_RETURNED";
    String LENDING_RETURNED_FAILED = "LENDING_RETURNED_FAILED";
    String LENDING_UPDATED = "LENDING_UPDATED";
    String LENDING_FAILED = "LENDING_FAILED";
    String LENDING_RETURNED_FINAL = "LENDING_RETURNED_FINAL";
}
