version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "monitor=true"  # Label para ser capturada pelo Prometheus
