services:
    users:
        image: lmsusers:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8094:8080"
        environment:
            SPRING_PROFILES_ACTIVE: bootstrap, relational, firebase
        deploy:
            replicas: 2
        networks:
            - lms_network2

    postgres_in_lms_network:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        deploy:
            replicas: 1
        ports:
            - "5447:5432"
        networks:
            - lms_network2
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres" ]
            interval: 10s
            retries: 5
            timeout: 5s

networks:
    lms_network2:
        external: true
