services:
  users:
    image: lmsusers:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8093-8097:8080"
    environment:
      SPRING_PROFILES_ACTIVE: test, bootstrap, relational, firebase
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_in_lms_network_user:5432/test_users_{{.Task.Slot}}?currentSchema=public
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - lms_network2
    deploy:
      replicas: 2
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - "uploaded_files_volume1:/tmp"

  postgres_in_lms_network_user:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5447-5450:5432"
    volumes:
      - "postgres_volume1:/var/lib/postgresql/data"
    networks:
      - lms_network2
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s
    deploy:
      replicas: 2

  nginx_user:
    image: nginx:latest
    restart: unless-stopped
    deploy:
      replicas: 1
    ports:
      - "81:80"
      - "444:443"
    networks:
      - lms_network2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  uploaded_files_volume1:
  postgres_volume1:

networks:
  lms_network2:
    external: true
