services:
  users:
    image: lmsusers:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8094-8097:8080"
    environment:
      SPRING_PROFILES_ACTIVE: test, bootstrap, relational, firebase
    networks:
      - lms_network2
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - "uploaded_files_volume:/tmp"

  postgres_in_lms_network_user:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5447-5450:5432"
    volumes:
      - "postgres_volume:/var/lib/postgresql/data"
    networks:
      - lms_network2
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s
    deploy:
      mode: replicated
      replicas: 2

volumes:
  uploaded_files_volume:
  postgres_volume:

networks:
  lms_network2:
    external: true
