services:
    users:
        image: lmsusers:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8086:8080"
        environment:
            SPRING_PROFILES_ACTIVE: bootstrap, relational, firebase
        networks:
            - lms_network2
        volumes:
            - "uploaded_files_volume:/tmp"
        deploy:
            mode: replicated

volumes:
    uploaded_files_volume:

networks:
    lms_network2:
        external: true
