
services:
  lmslendings_1:
    image: lmslendings:latest
    container_name: lendings1_in_lms_network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: bootstrap, relational, IDService1, alg1
    networks:
      - lms_network
    volumes:
      - "uploaded_files_volume_1:/tmp"

  lmslendings_2:
    image: lmslendings:latest
    container_name: lendings2_in_lms_network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    environment:
      SPRING_PROFILES_ACTIVE: bootstrap, relational, IDService1, alg1
    networks:
      - lms_network
    volumes:
      - "uploaded_files_volume_2:/tmp"

networks:
  lms_network:
    external: true

volumes:
  uploaded_files_volume_1:
  uploaded_files_volume_2: