services:
  lmslendingsQuery:
    image: lmslendingscommand:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOSTNAME}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: bootstrap, relational, IDService1, alg1
    networks:
      - lms_network
    volumes:
      - "uploaded_files_volume:/tmp"
    deploy:
      replicas: 2

networks:
  lms_network:
    external: true

volumes:
  uploaded_files_volume:
