@startuml

package "Client Machine" {
  [Browser]
}

package "Application Server" {
  artifact "psoft-g1.jar" as app
  artifact "MySQL Database" as mysql
  artifact "Sql Server Database" as sqlserver
  artifact "MongoDB Database" as mongodb
  artifact "Redis Database" as redis
}

package "IAM Providers" {
  [Google IAM]
  [Facebook IAM]
  [Azure IAM]
}

Browser --> app: HTTP Requests
app --> mysql: JDBC Connection
app --> sqlserver: JDBC Connection
app --> mongodb: NoSQL Connection
app --> redis: Key-Value Store Connection
app --> [Google IAM]: Authentication Request
app --> [Facebook IAM]: Authentication Request
app --> [Azure IAM]: Authentication Request

@enduml
